Fix Java 8 Compatibility Issue.
Issue:
If we compile this class with JDK13(or any JDK releases after JDK8), and running it with JDK8, it produces a exception like below:
    "Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;"

Cause:
The ByteBuffer override method rewind with a different return type ByteBuffer Since JDK9.When bytecodes generated by JDK13 and running with Java8, JVM will try to find a method match the method descriptor "java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer" and it will fail.